<?php
if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_daily-hours-2',
        'title' => 'Daily Hours',
        'fields' => array (
            array (
                'key' => 'field_54da7775fad60',
                'label' => 'Monday Open',
                'name' => 'monday_open',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da7785fad61',
                'label' => 'Monday Close',
                'name' => 'monday_close',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da78313002b',
                'label' => 'Tuesday Open',
                'name' => 'tuesday_open',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da78423002c',
                'label' => 'Tuesday Close',
                'name' => 'tuesday_close',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da78713002d',
                'label' => 'Wednesday Open',
                'name' => 'wednesday_open',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da78853002e',
                'label' => 'Wednesday Close',
                'name' => 'wednesday_close',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da789d50406',
                'label' => 'Thursday Open',
                'name' => 'thursday_open',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da78af50407',
                'label' => 'Thursday Close',
                'name' => 'thursday_close',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da78c2ef33d',
                'label' => 'Friday Open',
                'name' => 'friday_open',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da78ceef33e',
                'label' => 'Friday Close',
                'name' => 'friday_close',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da78e26ac7b',
                'label' => 'Saturday Open',
                'name' => 'saturday_open',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da78f06ac7c',
                'label' => 'Saturday Close',
                'name' => 'saturday_close',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da79012d3d8',
                'label' => 'Sunday Open',
                'name' => 'sunday_open',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
            array (
                'key' => 'field_54da79142d3d9',
                'label' => 'Sunday Close',
                'name' => 'sunday_close',
                'type' => 'date_time_picker',
                'show_date' => 'false',
                'date_format' => 'm/d/y',
                'time_format' => 'h:mm tt',
                'show_week_number' => 'false',
                'picker' => 'select',
                'save_as_timestamp' => 'true',
                'get_as_timestamp' => 'false',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'libhours_post_type',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_schedule-types',
        'title' => 'Schedule Types',
        'fields' => array (
            array (
                'key' => 'field_54dbb4f963370',
                'label' => 'Schedule Type',
                'name' => 'schedule_type',
                'type' => 'select',
                'instructions' => 'Only one Branch calendar per website.',
                'choices' => array (
                    'branch' => 'Branch',
                    'collection' => 'Collection',
                    'department' => 'Department',
                ),
                'default_value' => 'branch:Branch',
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'libhours_post_type',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'side',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_calendar-active',
        'title' => 'Calendar Active',
        'fields' => array (
            array (
                'key' => 'field_54f75034814fd',
                'label' => 'Calendar Active',
                'name' => 'calendar_active',
                'type' => 'radio',
                'required' => 1,
                'choices' => array (
                    'no' => 'No',
                    'yes' => 'Yes',
                ),
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => 'no',
                'layout' => 'horizontal',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'libhours_post_type',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'side',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 1,
    ));
    register_field_group(array (
        'id' => 'acf_semester',
        'title' => 'Semester',
        'fields' => array (
            array (
                'key' => 'field_54f752b05a372',
                'label' => 'Semester',
                'name' => 'semester',
                'type' => 'select',
                'choices' => array (
                    'spring' => 'Spring',
                    'fall' => 'Fall',
                    'summer' => 'Summer',
                    'winter' => 'Winter',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_54f752dc5a373',
                'label' => 'Year',
                'name' => 'year',
                'type' => 'number',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array (
                'key' => 'field_54f752f0d8109',
                'label' => 'Semester Begin',
                'name' => 'semester_begin',
                'type' => 'date_picker',
                'date_format' => 'yymmdd',
                'display_format' => 'dd/mm/yy',
                'first_day' => 1,
            ),
            array (
                'key' => 'field_54f75301d810a',
                'label' => 'Semester End',
                'name' => 'semester_end',
                'type' => 'date_picker',
                'date_format' => 'yymmdd',
                'display_format' => 'dd/mm/yy',
                'first_day' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'libhours_post_type',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'side',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 3,
    ));
}

?>